# -*- coding: utf-8 -*-
"""Copy of Chess Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KAZFAmDgkvDB6fQLtgoGQgB4zapHTwE8
"""

import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('precision', 2)

# Reading the CSV File
df = pd.read_csv('games.csv')

# Drop the columns that are not needed
df = df.drop(['name1', 'name2', 'name3...'], axis = 1)

# Check what the dataframe looks like
df

df.head()

# What percent of the games did white win? black?
list(df['winner']).count('white')*100/len(df)
#Black
list(df['winner']).count('black')*100/len(df)

# Average turns for each of the victory statuses?
num_turns = list(df['turns'])
victory_status = list(df['victory_status'])
status = {}
for i in range(len(num_turns)):
  if victory_status[i] not in status.keys():
    status[victory_status[i]] = []
status[victory_status[i]].append(num_turns[i])
for move, turn in status.items():
  print(move)
  print(sum(turns)/len(turns))

# Most popular opening moves?
openings = list(df['opening_name'])
all_openings = {}
for opening in openings:
  if opening not in all_openings.keys():
    all_openings[opening] = 0
  all_openings[opening] += 1

# How many distinct players are in this dataset?
len(df['id'].unique())

# Any conclusions that can be drawn from the moves?